export const IMAGE_TOKENS = {
    SERVICES: {
        QUERY: Symbol('IMAGE_QUERY_SERVICE'),
        COMMAND: Symbol('IMAGE_COMMAND_SERVICE'),
        TRANSFORM: Symbol('IMAGE_TRANSFORM_SERVICE'),
        VARIANT_QUERY: Symbol('IMAGE_VARIANT_QUERY_SERVICE'),
        VARIANT_COMMAND: Symbol('IMAGE_VARIANT_COMMAND_SERVICE'),
    },
    REPOSITORIES: {
        QUERY: Symbol('IMAGE_QUERY_REPOSITORY'),
        COMMAND: Symbol('IMAGE_COMMAND_REPOSITORY'),
        VARIANT_COMMAND: Symbol('IMAGE_VARIANT_COMMAND_REPOSITORY'),
        VARIANT_QUERY: Symbol('IMAGE_VARIANT_QUERY_REPOSITORY'),
    },
} as const;
